# Generated by Django 5.1.7 on 2025-03-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='is_core',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.academicyear'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.academicyear'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.academicyear')),
            ],
            options={
                'unique_together': {('academic_year', 'semester_number')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.semester'),
        ),
        migrations.CreateModel(
            name='YearProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_core', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.academicyear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.program')),
            ],
            options={
                'unique_together': {('program', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='academicyear',
            name='programs',
            field=models.ManyToManyField(through='university.YearProgram', to='university.program'),
        ),
    ]
