# Generated by Django 5.1.7 on 2025-03-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_academicyear_subject_is_core_student_current_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='start_date',
        ),
    ]
