# Generated by Django 5.1.7 on 2025-03-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_semester_end_date_remove_semester_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
